---
image: debian/stable
packages:
  - bash
  - dash
  - mksh
  - zsh
  - bc
tasks:
  - test-bash: |
      cd libencode.sh/regress/
      bash encode.t
      bash base64-nodejs.t
      bash pathexpan.t
      bash rfc4648.t
  - test-dash: |
      cd libencode.sh/regress/
      dash encode.t
      dash base64-nodejs.t
      dash pathexpan.t
      dash rfc4648.t
  - test-mksh: |
      cd libencode.sh/regress/
      mksh encode.t
      mksh base64-nodejs.t
      mksh pathexpan.t
      mksh rfc4648.t
  - test-zsh: |
      cd libencode.sh/regress/
      zsh encode.t
triggers:
  - action: email
    condition: failure
    to: "<tleguern+kbf@bouledef.eu>"
